- hosts: localhost                                                     
  tasks:
  - name: Install github python package
    pip:
      name: github3.py
  - name: Add grafana repo
    yum_repository:
      name: grafana
      description: Grafana enterprise repo
      file: grafana.repo
      baseurl: https://packages.grafana.com/enterprise/rpm
      gpgcheck: no
  - name: Install grafana
    yum:
      name: grafana
      state: present
  - name: Enable and start grafana
    ansible.builtin.systemd:
      daemon_reload: yes
      state: started
      name: grafana-server
      enabled: yes
  - name: Get latest release of filestat_exporter
    community.general.github_release:
      user: michael-doubez
      repo: filestat_exporter
      action: latest_release
  - name: Get latest release of prometheus
    community.general.github_release:
      user: prometheus
      repo: prometheus
      action: latest_release
  - name: Get latest release of node_exporter
    community.general.github_release:
      user: prometheus
      repo: node_exporter
      action: latest_release